version: '3.8'

services:
  fuelcost:
    build: ./fuelcost
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - app-network

  personal_service:
    build: ./personal_service
    expose:
      - "8081"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fuelcost
      - personal_service
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot 
    command: certonly --webroot -w /var/www/certbot --force-renewal --email blackshadowsoftwareltd@gmail.com -d fuelcost.blackshadow.software -d personal_service.blackshadow.software --agree-tos

networks:
  app-network:
    driver: bridge