version: "3.8"

services:
  fuel_cost_server:
    build: ./fuel_cost_server
    expose:
      - "8880" # Match your Rust server port
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1 # Add backtrace for debugging
    networks:
      - app-network
    healthcheck: # Add health check
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # personal_service:
  #   build: ./personal_service
  #   expose:
  #     - "8081"
  #   restart: unless-stopped
  #   environment:
  #     - RUST_LOG=info
  #   networks:
  #     - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      fuel_cost_server:
        condition: service_healthy # Wait for health check
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
