version: "3.3"

services:
  fuel_cost_server:
    build: ./fuel_cost_server
    expose:
      - "8880"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - app-network

  # personal_service:
  #   build: ./personal_service
  #   expose:
  #     - "8081"
  #   restart: unless-stopped
  #   environment:
  #     - RUST_LOG=info
  #   networks:
  #     - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fuel_cost_server
      # - personal_service
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
